import Head from "next/head";

export default function Layout({children}) {
  return (
    <>
      <Head>
        <title>pentcloud-test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-600 min-h-screen flex flex-col">{children}</div>
    </>
  )
}

